# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f86f3ec19bbc8eec99dfbc0e60961e0bdc95bd2764a5d836fa419acca4b86fc97e25de370378d9659021095914f66c5478fd5a378014ede645e536a0968d5657

test:
  secret_key_base: da8c3518f449c62d043a47a62d892db4d86bfcb91af5e0af0a9782b2c141ea90a05cebc3ca5bf2ef318bacc12c65717c66aed753c4002ae272a8b99e4331a40b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
